baseURL = "https://timememo.lizhou31.com/"
relativeURLs = false
canonifyURLs = true
title = "TimeMemo"
theme = ["FixIt"]
themesDir = "themes/"

# Language settings
defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
hasCJKLanguage = true

# Enable features
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

# Ignore errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Author config
[author]
  name = "Lizhou"
  email = "lisie31s@gmail.com"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    url = "https://github.com/Lizhou31"
    title = "GitHub"
    weight = 5

[params]
  version = "0.3.X"
  description = "This is a memo to record my life, my learning, and my thoughts."
  keywords = ["Blog", "Hugo", "FixIt"]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  images = ["images/logo.ico"]
  
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "TimeMemo"
      pre = "<i class='fa fa-home'></i>"
      typeit = false

  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2022
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "TimeMemo"
    noFavicon = false
    svgFavicon = "/favicon.svg"
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "algolia"
    contentLength = 4000
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = "tm_index"
      appID = "6UTKX9KXC6"
      searchKey = "19c57b4257957fba5cee4821e7bf4dee"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpeg"
      title = "Lizhou's TimeMemo"
      subtitle = "A novice programmer, a beginner photographer, and an amateur writer."
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "Lizhou31"
    Instagram = "lizhou_ph"
    Telegram = "Lizhou0726"
    Discord = "392327187694354442"
    Email = "lisie31s@gmail.com"

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    
    [params.page.code]
      copy = true
      maxShownLines = 50

    [params.page.comment]
      enable = true
      [params.page.comment.utterances]
        enable = true
        # owner/repo
        repo = "Lizhou31/TimeMemo"
        issueTerm = "pathname"
        label = "Comments"
        lightTheme = "github-light"
        darkTheme = "github-dark"

  [params.typeit]
    speed = 60
    cursorSpeed = 1000
    cursorChar = "|"
    duration = 1400
    loop = false

  [params.gitInfo]
    repo = "https://github.com/Lizhou31/TimeMemo"
    enableEditLink = true
    branch = "main"

  [params.readingTime]
    enable = true
  
  [params.wordCount]
    enable = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":filename"

