baseURL = "https://timememo.lizhou31.com/"
languageCode = "en-us"
title = "TimeMemo"
theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 3

[[menu.main]]
name = "Blog"
url = "blog/"
weight = 2

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "Monday, Jan 2, 2006"
# Meta data
description = "TimeMemo, a Blog"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "僅僅是個興趣使然的"
description = "覺得自己什麼都不會，覺得自己什麼都該學"

# flip text
[[params.banner.flipText]]
title = "DEVELOPER"
[[params.banner.flipText]]
title = "Photographer"
[[params.banner.flipText]]
title = "Writer"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT ME"
content = "興趣使然的開始接觸程式，興趣使然的開始唸書，一切都是興趣使然，所以實際上水準很差。在求學的道路上並沒有一帆風順，過多的叛逆與貪玩幾乎浪費掉了那段時光，真正出了社會需要面對考驗的時候就只能，啊！我就爛 ^_^b"
image = "images/about/about.jpg"
gmail = "mailto:lisie31s@gmail.com"
github = "https://www.github.com/lizhou31"